### ISSUE TITLE
Request: Entities for individual relays controlling a pool pump

### ISSUE THREAD

**Issue by subcritical71** [Crewski/njsPC-HA#38]
As the title states, I have a Pentair Superflo VS pump which I am controlling via four relays (through REM). Basically,  the four relays are hooked up to one of four programs on the pump. Whichever relay is energized is the speed of the pump (if more than one relay is energized the highest program with a relay energized takes the priority. 

Your integration currently shows pump state and it is correct, but only gives me an On/Off state not speed. 

Is it possible to expose the relays in your integration? Or, maybe there is a better way to do something similar(?)

BTW, I have no idea what Status is supposed to show, it is always off and I seemed to remember it saying Blocked at one time. 
 
<img width="364" alt="Screen Shot 2023-07-06 at 4 25 00 PM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/739142a0-b91a-442d-ae04-5abcd9b82402">
<img width="629" alt="Screen Shot 2023-07-04 at 5 51 10 PM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/724b444f-39b2-4bf7-a0b9-0d84e4c5d17e">
<img width="324" alt="Screen Shot 2023-07-06 at 4 28 07 PM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/631e248e-8c20-4981-ade0-569477658a2d">

**Comment by Crewski** [comment]
Try to update to the latest version and check for a sensor called program.
I just pushed that update earlier today.

**Comment by subcritical71** [comment]
This is great but doesn't seem to be working for me. I get either '0' or 'Program #0' as the state. It also takes quite a while to update once a change is made.

<img width="587" alt="Screen Shot 2023-07-07 at 3 09 20 PM" src="https://github.com/Crewski/njsPC-HA/assets/12250429/b0663166-01ba-4b45-b5df-4a96210f5e16">

**Comment by Crewski** [comment]
I guess that's the difference between Hayward and Pentair for relay control.  Do it show what you are looking for in Dashpanel on the main page?  That way I can try to track it down.  Also, all of the events are not pushed to the event bus on HA, just go to the Events tab in Developer Tools and listen to `njspc-ha_event`.  Play with the speeds and see if you can find the differences.

**Comment by subcritical71** [comment]
Wow, I learned something new today. I never used the listen feature. Is there a way to only see a specific 'evt' type, in this case 'pump'?

What I was able to determine was that the number associated with the relay field (in this case relay: 2) specified the program number. Relay: 0 is off. Is this enough to work off of? I'm pretty new to this side of HA so if you have anything else you'd like to see I may just need a little nudge.

During all my testing, the value displayed in the status field never changed from 'Program #0'.

```
event_type: njspc-ha_event
data:
  evt: pump
  data:
    id: 50
    status:
      name: "off"
      desc: "Off"
      val: 0
    pumpOnDelay: false
    name: Filter Pump
    address: 96
    type:
      val: 100
      name: sf
      desc: SuperFlo VS
      hasAddress: false
      maxCircuits: 8
      maxRelays: 4
      equipmentMaster: 1
      maxSpeeds: 4
      relays:
        - id: 1
          name: "Program #1"
        - id: 2
          name: "Program #2"
        - id: 3
          name: "Program #3"
        - id: 4
          name: "Program #4"
    relay: 2
    isActive: true
    targetSpeed: 0
    driveState: 0
    command: 0
    event: pump
origin: LOCAL
time_fired: "2023-07-08T03:23:00.150180+00:00"
context:
  id: 01H4SRCCNP0D75CQCCNA9VA60Y
  parent_id: null
  user_id: null
```
