### ISSUE TITLE
Push sensor value from HA to njsPC

### ISSUE THREAD

**Issue by lymanepp** [Crewski/njsPC-HA#46]
I love this integration and I hope to make some contributions in the near future.

My air temperature sensor is below my controller enclosure and it diverges quite a bit from my weather station's air temperature during daytime. I created an automation to push my weather station temperature to njsPC (below). While this works fine, it would be cool if njsPC-HA had a way to do this without the automation.

```
automation:
  - alias: Synchronize temperature with Pool Controller
    description: ''
    trigger:
    - platform: state
      entity_id:
      - sensor.weatherflow_temperature
      to:
    condition:
    - condition: template
      value_template: '{{ trigger.to_state.state != "unavailable" }}'
    action:
    - service: shell_command.set_pool_air_sensor1
      data:
        temperature: '{{ trigger.to_state.state }}'
    mode: single

shell_command:
  set_pool_air_sensor1: >-
    curl -X PUT 'http://10.x.x.x:4200/state/temps' -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"airSensor1": {{temperature}}}'
```
